FORMAT: 1A
HOST: http://api.servicehouse.nl/

# User API

With this API user profile can be retrieved.

## User Profile [/api/v0/users/{id}/details]

### Get a User Profile [GET]

+ Response 200 (application/json)

        [
            {
                "first_name": "Frank",
                "prefix_name": "de",
                "last_name": "Bruin",
                "full_name": "Frank de bruin" 
                "address": {
                    "street":"Keizersgracht",  
                    "house_number":"112",
                    "extension":"2 Hoog"
                    "postalcode":"1022 AG"
                    "city":"Amsterdam"
                },
                "email_address":"fdebruin@xs4all.nl"
                "phone_number":"02023484838"
            }
        ]

### Update a User Profile [PATCH]

+ Request 

        {
            "phone_number":"02023484837"
        }

+ Response 204 (application/patch-json)